import { Geist, Geist_Mono, Reem_Kufi, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers/providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// আরবি ফন্ট (variable প্রপার্টি যুক্ত করা হয়েছে)
const reemKufi = Reem_Kufi({
    variable: "--font-reem-kufi",
    subsets: ['arabic'],
    weight: ['400', '500', '600', '700'], 
    display: "swap",
});

// বাংলা ফন্ট
const hindSiliguri = Hind_Siliguri({
    variable: "--font-hind-siliguri",
    subsets: ["bengali"],
    weight: ["300", "400", "500", "600", "700"],
    display: "swap",
});

export const metadata = {
    title: "As-Salam Ideal Madrasah  (AIM)",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en" // অথবা প্রয়োজন অনুযায়ী "bn" বা "ar" দিতে পারেন
            className={`${geistSans.variable} ${geistMono.variable} ${reemKufi.variable} ${hindSiliguri.variable} h-full antialiased`}
        >
            {/* বডিতে ডিফল্টভাবে বাংলা ফন্ট চালু রাখতে hindSiliguri.className যোগ করতে পারেন */}
            <body className={`${hindSiliguri.className} min-h-full flex flex-col`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
