import { Geist, Geist_Mono, Reem_Kufi } from "next/font/google"; // ১. Reem_Kufi ইম্পোর্ট করা হলো
import "./globals.css";
import Providers from "@/components/Providers/providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// ২. Reem Kufi ফন্টটি এখানে কনফিগার করা হলো (শুধু আরবির জন্য)
const reemKufi = Reem_Kufi({
    variable: "--font-reem-kufi",
    subsets: ["arabic"],
    weight: ["400", "700"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            // ৩. এখানে ${reemKufi.variable} ক্লাসটি যোগ করে দেওয়া হলো
            className={`${geistSans.variable} ${geistMono.variable} ${reemKufi.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Providers> {children}</Providers>
            </body>
        </html>
    );
}


// MONGODB_URI=mongodb+srv://aimhabiganj:UZuWSyT3e3QYNal@cluster0.w9cbrwo.mongodb.net/?appName=Cluster0
// # GEMINI_API_KEY=
// BETTER_AUTH_URL=http://localhost:3000
// BETTER_AUTH_SECRET=E1NnJYqNWZq0OIw49znddHpNbp4U2IAC
// NEXT_PUBLIC_SERVER_API=http://localhost:5000
// NEXT_PUBLIC_IMGBB_API_KEY=5a4f8c279ddcedf0d73f50444bad88b0