import { Geist, Geist_Mono, Reem_Kufi } from "next/font/google"; // ১. Reem_Kufi ইম্পোর্ট করা হলো
import "./globals.css";
import Providers from "@/components/Providers/providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// ২. Reem Kufi ফন্টটি এখানে কনফিগার করা হলো (শুধু আরবির জন্য)
const reemKufi = Reem_Kufi({
    variable: "--font-reem-kufi",
    subsets: ["arabic"],
    weight: ["400", "700"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            // ৩. এখানে ${reemKufi.variable} ক্লাসটি যোগ করে দেওয়া হলো
            className={`${geistSans.variable} ${geistMono.variable} ${reemKufi.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Providers> {children}</Providers>
            </body>
        </html>
    );
}
